/**
 * Writes public/sitemap.xml from the route list in core/seo/seo-content.ts, so the
 * sitemap can't drift from the brand handles the app actually serves.
 *
 * Runs BEFORE `ng build` (see package.json), so the file it writes is picked up by the
 * same build's asset copy rather than landing in dist one build late.
 *
 * Node only strips types — it does not resolve extensionless imports — so this may only
 * import modules that are themselves import-free. `seo-content.ts` is written that way
 * on purpose; don't add imports to it.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SEO_PAGES, SITEMAP_PATHS } from '../src/app/core/seo/seo-content.ts';

const SITE_URL = 'https://josephbattisti.com';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'sitemap.xml');

/** Home outranks the hubs, which outrank individual brand collections. */
function priorityFor(path: string): string {
  if (path === '/') return '1.0';
  if (path === SEO_PAGES.services.path || path === SEO_PAGES.shop.path) return '0.9';
  if (path.startsWith('/shop/brand/')) return '0.6';
  return '0.8';
}

function changefreqFor(path: string): string {
  return path.startsWith('/shop') || path === '/sale' ? 'weekly' : 'monthly';
}

const lastmod = new Date().toISOString().slice(0, 10);

const body = SITEMAP_PATHS.map(
  (path) => `  <url>
    <loc>${SITE_URL}${path === '/' ? '/' : path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreqFor(path)}</changefreq>
    <priority>${priorityFor(path)}</priority>
  </url>`,
).join('\n');

writeFileSync(
  OUT,
  `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.ts — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`,
  'utf8',
);

console.log(`sitemap.xml: ${SITEMAP_PATHS.length} urls -> ${OUT}`);
